# test-bad-sa-token.yaml
# Expected: BLOCKED by block-automount-sa-token policy
apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-sa-token
  namespace: demo
spec:
  automountServiceAccountToken: true
  containers:
  - name: test
    image: alpine
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
